#!/bin/bash

git_tips=$(cat <<-EOF
    Useful $1:
    git blame file                    #Find out who wrote the code
    git blame -L start,end file       #Same but specify specific lines
EOF
)

vim_tips=$(cat <<-EOF
    Useful $1:
    gj/gk               move cursor down/up multiline text
    H                   move to top of the screen
    M                   move to middle of the screen
    L                   move to bottom of the screen
    w                   jump forwards to the start of a word
    W                   jump forwards to the start of a word with punctuation
    e                   jump forwards to the end of a word
    E                   jump forwards to the end of a word with punctuation
    b                   jump backwards to the start of a word
    B                   jump backwards to the start of a word with punctuation
    ge                  jump backwards to the end of a word
    gE                  jump backwards to he end of a word with punctuation
    %                   move cursor to matching character
    Ctrl + t            tab/indent right (insert mode)
    Ctrl + d            tab/indent left (insert mode)
EOF
)

cz_tips=$(cat <<-EOF
    fn+2    ě
    fn+3    š
    fn+4    č
    fn+5    ř
    fn+6    ž
    fn+7    ý
    fn+8    á
    fn+9    í
    fn+0    é

    {[ (right to P)         ú
    :; (right to L)         ů
    += (before backspace)   ´
    ´ + o                   ó
    ´  + shift + d,t,n      ď ť ň
EOF
)

case "$1" in
    git)
        output="$git_tips"
        ;;
    vim)
        output="$vim_tips"
        ;;
    cz)
        output="$cz_tips"
        ;;
    *)
        echo "Usage: useful {git|vim|cz} [keyword]"
        exit 1
        ;;
esac

if [ -n "$2" ]; then
    echo "$output" | grep -i "$2"
else
    echo "$output"
fi

exit 0
